const contentType = [
    { id: 0, code: "MID" },
    { id: 1, code: "PHONE" },
    { id: 2, code: "EMAIL" },
    { id: 3, code: "USERID" },
    { id: 4, code: "PROXIMITY" },
    { id: 5, code: "GROUP" },
    { id: 6, code: "USER" },
    { id: 7, code: "QRCODE" },
    { id: 8, code: "PROMOTION_BOT" },
    { id: 9, code: "CONTACT_MESSAGE" },
    { id: 10, code: "FRIEND_REQUEST" },
    { id: 11, code: "REPAIR" },
    { id: 12, code: "FACEBOOK" },
    { id: 13, code: "SINA" },
    { id: 14, code: "RENREN" },
  ];
  const MIDType = [
    { id: 0, code: "USER" },
    { id: 1, code: "ROOM" },
    { id: 2, code: "GROUP" },
    { id: 3, code: "SQUARE" },
    { id: 4, code: "SQUARE_CHAT" },
    { id: 5, code: "SQUARE_MEMBER" },
    { id: 6, code: "BOT" },
  ];
  const msgType = [
    { id: 0, code: "NONE" },
    { id: 1, code: "IMAGE" },
    { id: 2, code: "VIDEO" },
    { id: 3, code: "AUDIO" },
    { id: 4, code: "HTML" },
    { id: 5, code: "PDF" },
    { id: 6, code: "CALL" },
    { id: 7, code: "STICKER" },
    { id: 8, code: "PRESENCE" },
    { id: 9, code: "GIFT" },
    { id: 10, code: "GROUPBOARD" },
    { id: 11, code: "APPLINK" },
    { id: 12, code: "LINK" },
    { id: 13, code: "CONTACT" },
    { id: 14, code: "FILE" },
    { id: 15, code: "LOCATION" },
    { id: 16, code: "POSTNOTIFICATION" },
    { id: 17, code: "RICH" },
    { id: 18, code: "CHATEVENT" },
    { id: 19, code: "MUSIC" },
    { id: 20, code: "PAYMENT" },
    { id: 21, code: "EXTIMAGE" },
    { id: 22, code: "FLEX" },
  ];

  module.exports = {contentType,MIDType,msgType}